
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Librarians For Broadband"
theme = "basic"
[Params]
author = "TJ Lamanna"
description = "Librarians For Broadband"
gh_url = "https://api.github.com/users"
gh_user = "TLamanna"